services:
  backend:
    build:
      context: .
      dockerfile: docker/django/Dockerfile
    container_name: hotel_backend
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/hotel-paso-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
